--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-keptn-test-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: project-keptn-test-service
  template:
    metadata: 
      labels:
        app: project-keptn-test-service
    spec:
      containers:
      - name: project-keptn-test-service
        image: "{{ .Values.image }}"

        env:
        - name: KEPTN_PROJECT
          value: "{{ .Chart.Name }}"
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: KEPTN_SERVICE
          value: "{{ .Values.service.name }}"
