apiVersion: v1
kind: Service
metadata:
  name: project-keptn-test-service
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: null
  selector:
    app: project-keptn-test-service
